import "../styles/globals.css";

import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";

export const metadata: Metadata = {
  title: "Codezinc",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/image.png" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${GeistSans.variable}`}>
      <body className="bg-foreground-default h-screen w-[100%] px-[12.5%]">
        {children}
      </body>
    </html>
  );
}
